### ISSUE TITLE
Built-in Support of Timeout Event

### ISSUE THREAD

**Issue by JitCompiler** [etgryphon/stativus#55]
I found that I often need to include a Timeout event in various substates (e.g. waiting for AJAX response).  Currently, the way I achieve this is to update a single global startTime variable in all my substate's enterstate function and have some routine to generate the Timeout event by checking against this startTime variable.  But this cause duplicate code in all my substates' enterstate function.

I think timeout is such a universal event that some sort of built-in support is appropriate.  Perhaps, the simplest way is to expose an automatically updated global variable in statechart  object that shows the time that the last change of state occurred.

**Comment by Katahdin** [comment]
Child states have access to parent variables stored with setData.

I would use setData("timeout", timeOut) in the parent state.  Then use getData("timeout") to retrieve the it in the child state.

**Comment by etgryphon** [comment]
@Katahdin is right about it.  I usually follow this pattern:
```
enterState: function(){
  var timer = setInterval(function(){
  var dd = that.getData("diagramData");
    myStatechart.sendEvent("loadProcessDiagramActivities", dd.id);
  }, PD_ACT_MIN_REFRESH*60*1000);
  this.setData('timer', timer);
},

exitState: function(){
  var timer = this.getData('timer');
  clearInterval(timer);
},
```
