### ISSUE TITLE
Documentation and demo site seems to be down

### ISSUE THREAD

**Issue by brucou** [etgryphon/stativus#94]
I am referring to 

- http://www.stativ.us/
- http://etgryphon.github.com/stativus/

Can they be found somewhere else? Documentation would be amazing.

**Comment by 140am** [comment]
You can find the site source code in the [gh-pages](https://github.com/etgryphon/stativus/tree/gh-pages) branch of this repository. 

> git clone https://github.com/etgryphon/stativus  
> cd stativus  
> git checkout gh-pages  
> make  

If you want to view it locally in your browser simply edit the generated `stativus/index.html` and change `/assets/app.css` to `./assets/app.css` at the beginning of the file and `/assets/app.js` to `./assets/app.js` as well `<script src="//ajax.google...` to `<script src="http://ajax.google..` at the end of the file.
